import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FeatureRecord {
  /** UUID uniquely identifying this feature run */
  id: string;
  /** ISO 8601 — when the feature file / Linear issue was first detected */
  requestedAt: string;
  /** ISO 8601 — when processing finished (success or error) */
  completedAt: string;
  /** Wall-clock duration reported by the SDK (ms) */
  executionTimeMs: number;
  /** Claude model used for the main agent run */
  model: string;
  /** Prompt tokens sent to the API */
  tokensIn: number;
  /** Completion tokens received from the API */
  tokensOut: number;
  /** Tokens served from the prompt cache */
  cacheReadTokens: number;
  /** Tokens written into the prompt cache */
  cacheWriteTokens: number;
  /** Total USD cost of the agent run (main model only) */
  totalCostUsd: number;
  /** Number of agent turns (tool-call / response cycles) */
  numTurns: number;
  /** All files that changed during this feature run */
  filesChanged: string[];
  /** Subset of filesChanged that are test files */
  testsAdded: string[];
  /** Git branch active during processing */
  gitBranch: string;
  /** SHA of the commit created after the feature, or null if none */
  gitCommitHash: string | null;
  /** Original feature description (text before ## Plan) */
  description: string;
  /** Plan checkbox items (text only, without checkbox syntax) */
  planPoints: string[];
  /** Whether triggered from a features/ file or a Linear issue */
  source: "file" | "linear";
  /** Linear internal UUID (null when source === "file") */
  linearIssueId: string | null;
  /** Human-readable Linear identifier, e.g. "PROJ-42" (null when source === "file") */
  linearIdentifier: string | null;
  /** Outcome of the feature run */
  status: "success" | "error";
  /** Error detail when status === "error", otherwise null */
  errorMessage: string | null;
  /** AI-generated short title (20-80 chars) for the feature */
  title: string;
  /** 2-3 sentence summary generated by a low-cost model after completion */
  summary: string;
}

// ---------------------------------------------------------------------------
// Storage
// ---------------------------------------------------------------------------

const DB_PATH = ".kaibot/features.json";

function dbPath(projectDir: string): string {
  return join(projectDir, DB_PATH);
}

function readDb(projectDir: string): FeatureRecord[] {
  const path = dbPath(projectDir);
  if (!existsSync(path)) return [];
  try {
    const raw = readFileSync(path, "utf8");
    const parsed = JSON.parse(raw) as unknown;
    return Array.isArray(parsed) ? (parsed as FeatureRecord[]) : [];
  } catch {
    return [];
  }
}

/**
 * Appends a single FeatureRecord to `.kaibot/features.json` in the given
 * project directory.  Creates the directory and file if they don't exist.
 */
export function appendFeatureRecord(projectDir: string, record: FeatureRecord): void {
  const path = dbPath(projectDir);
  mkdirSync(join(projectDir, ".kaibot"), { recursive: true });
  const records = readDb(projectDir);
  records.push(record);
  writeFileSync(path, JSON.stringify(records, null, 2) + "\n");
}
