import { KaiClient } from "./KaiClient.js";

// ---------------------------------------------------------------------------
// Prompt
// ---------------------------------------------------------------------------

function buildTechDebtPrompt(projectDir: string): string {
  return `You are a senior software engineer performing a comprehensive code review of an existing codebase.

**Project directory:** ${projectDir}

## Your task

Scan ALL source code files in this project and identify technical debt items. Explore the codebase thoroughly — read key source files, look for patterns and anti-patterns.

Create a prioritized TODO list covering:
- **Security** — vulnerabilities, unsafe patterns, insecure dependencies, missing input validation
- **Refactoring** — complex or tangled code, poor separation of concerns, overly long functions, magic numbers/strings
- **Documentation** — missing or outdated comments, undocumented public APIs, unclear variable/function names
- **Code cleanup** — dead code, unused imports/variables, commented-out code, inconsistent style
- **Duplicate code** — repeated logic that should be extracted into shared utilities
- **Code quality** — missing error handling, overly nested logic, brittle patterns, poor testability
- **Performance** — obvious inefficiencies, N+1 patterns, unnecessary re-computation
- **Dependencies** — outdated packages, unnecessary dependencies

## Output

Write a \`todo.md\` file in the project root with this format:

\`\`\`markdown
# Tech Debt TODO

_Generated by KaiBot tech debt scan._

## High Priority

- [ ] **[Security]** Description of the issue — file/location
- [ ] **[Refactoring]** Description of the issue — file/location

## Medium Priority

- [ ] **[Documentation]** Description of the issue — file/location
- [ ] **[Code Cleanup]** Description of the issue — file/location

## Low Priority

- [ ] **[Duplicate Code]** Description of the issue — file/location
- [ ] **[Performance]** Description of the issue — file/location
\`\`\`

Be specific and actionable. Include the file name and line numbers where possible. Focus on real issues — don't invent problems. Aim for 10–30 concrete items.`;
}

// ---------------------------------------------------------------------------
// runTechDebtScan
// ---------------------------------------------------------------------------

/**
 * Runs an agent scan of the project codebase and writes a prioritized tech
 * debt TODO list to `todo.md` in the project root directory.
 *
 * The agent uses its filesystem tools (Read, Glob, Grep) to explore the
 * codebase and then writes the results with its Write tool.
 *
 * @returns The absolute path of the written `todo.md` file.
 */
export async function runTechDebtScan(projectDir: string, model: string): Promise<string> {
  const client = KaiClient.create(projectDir, model);
  const prompt = buildTechDebtPrompt(projectDir);

  // run() drives the full agent loop (including tool calls) to completion
  await client.run(prompt);

  return `${client.projectDir}/todo.md`;
}
